# Inject CA bundle using cert-manager annotation
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: skipjobs.skiperator.kartverket.no
  annotations:
    cert-manager.io/inject-ca-from: skiperator-system/skiperator-webhook-ca
