apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: application-sample
spec:
  image: "wardsco/sleep:latest"
  port: 8080
  ingresses:
  - testapp.dev.skip.statkart.no
  replicas:
    min: 3
    max: 5
    targetCpuUtilization: 80
  env:
  - name: ENV
    value: PRODUCTION
  - name: NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  filesFrom:
  #- configmap: some-configmap
  #  mountPath: /var/run/configmap
  #- secret: some-secret
  #  mountPath: /var/run/secret
  #- persistentVolumeClaim: some-pvc
  #  mountPath: /var/run/volume
  liveness:
    path: /healthz
    port: 8080
  resources:
    limits:
      cpu: "1000m"
      memory: "1G"
    requests:
      cpu: "1000m"
  accessPolicy:
    inbound:
      rules:
      - application: other-app
      - application: third-app
        namespace: other-namespace
    outbound:
      rules:
      - application: other-app
      external:
      - host: nrk.no
      - host: smtp.mailgrid.com
        ports: 
        - name: smtp
          protocol: TCP
          port: 587