apiVersion: v1
kind: ConfigMap
metadata:
  name: skiperator-config
  namespace: skiperator-system
data:
  config.json: |
    {
      "topologyKeys": [
        "kubernetes.io/hostname",
        "onprem.gke.io/failure-domain-name"
      ],
      "leaderElection": false,
      "leaderElectionNamespace": "skiperator-system",
      "concurrentReconciles": 1,
      "isDeployment": false,
      "logLevel": "error",
      "registrySecretRefs": [
        {
          "registry": "ghcr.io",
          "secretName": "github-config",
          "secretKey": "token"
        },
        {
          "registry": "https://index.docker.io/v1/",
          "secretName": "docker-config",
          "secretKey": "token"
        }
      ],
      "clusterCIDRExclusionEnabled": true,
      "clusterCIDRMap": {
        "clusters": [
          {
            "name": "test-cluster-1",
            "controlPlaneCIDRs": [
              "10.40.10.0/25"],
            "workerNodeCIDRs": [
              "10.40.10.0/24"]
          }
        ]
      },
      "gcpIdentityProvider": "testProvider",
      "gcpWorkloadIdentityPool": "testPool",
      "enableWebhooks": true
    }
