apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../skiperator.kartverket.no_skipjobs.yaml

patches:
  - path: ../patches/webhook_in_skipjobs.yaml
  - path: ../patches/cainjection_in_skipjobs.yaml

configurations:
  - ../kustomizeconfig.yaml
